name: Meilisearch

on:
  workflow_dispatch:

jobs:
  meilisearch:
    name: Meilisearch
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY_API}}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.GCP_CLOUD_RUN_SERVICE_NAME_MEILISEARCH }}
          region: ${{ vars.GCP_REGION }}
          image: getmeili/meilisearch:latest
          flags: |
            --port 7700
            --timeout 300
            --platform=managed
            --add-volume name=meilisearch-data,type=cloud-storage,bucket=${{ secrets.GCP_MEILISEARCH_BUCKETNAME }}
            --add-volume-mount volume=meilisearch-data,mount-path=/meili_data
            --allow-unauthenticated
          env_vars: |
            MEILI_ENV=production
            MEILI_HTTP_ADDR=0.0.0.0:7700
          secrets: |
            MEILISEARCH_API_KEY=MEILISEARCH_API_KEY:latest

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}